# Generated by Django 5.1.5 on 2025-01-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_alter_sucursal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='identificacion',
            field=models.CharField(editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='numero',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
