# Generated by Django 5.1.5 on 2025-01-26 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_alter_empleado_identificacion_alter_sucursal_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='registro',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema.registro'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal', to='Sistema.direccion'),
        ),
    ]
