# Generated by Django 5.1.5 on 2025-01-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='traer_de_otra_sucursal',
            field=models.BooleanField(default=False),
        ),
    ]
