# Generated by Django 5.1.5 on 2025-01-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0008_remove_venta_es_para_retirar_pedido_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='traer_de_otra_sucursal',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
