# Generated by Django 5.1.5 on 2025-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_alter_pedido_cliente_alter_venta_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
