# Generated by Django 5.1.5 on 2025-01-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0011_alter_venta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
