# Generated by Django 5.1.5 on 2025-01-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0012_alter_venta_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='inventario',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='farmacia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='Sistema.farmacia'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_list', to='Sistema.inventario')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_list', to='Sistema.medicamento')),
            ],
        ),
    ]
