# Generated by Django 5.1.5 on 2025-01-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0014_venta_esta_pagado_alter_venta_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='esta_pagado',
        ),
    ]
